### ISSUE TITLE
I can't run the  examples.

### ISSUE THREAD

**Issue by Alpagateau** [caslabuiowa/BeBOT#1]
Hello, I have a problem with cartopy. I can't install it so I can't run your code. What can I do ?

**Comment by magicbycalvin** [comment]
What manager are you using for Python? For the time being, I would recommend simply commenting out the code which uses cartopy which will remove the flight example. However, I will create a yaml file which can be used to import the same environment I've got in Anaconda.

**Comment by magicbycalvin** [comment]
I just added the YAML file. If you are running Anaconda on Windows, you should be able to run Anaconda Navigator and import the environment. Otherwise, you can run `conda env create -f bebotenv.yml` on the Linux command line.

**Comment by Alpagateau** [comment]
is it possible to use it without anaconda ?

Le mer. 1 juil. 2020 à 00:52, magicbycalvin <notifications@github.com> a
écrit :

**Comment by magicbycalvin** [comment]
Yeah it should work just fine as long as you have the required packages. If you look inside the YAML file I uploaded, there is a list of packages which you should be able to install via pip.

**Comment by magicbycalvin** [comment]
@Alpagateau was that able to solve your problem?
